% File: ky4dSubjects.m

gt_subjects = {'abe', 'dai', 'furu', 'iketani', 'ima', 'inai',... 
    'jo', 'kaku', 'kawa', 'kimura', 'koga', 'kura',... 
    'kuroki', 'maeno', 'maruyama', 'matsui', 'matsumoto', 'matsuo', 'mori', 'mouri', ...
    'murayama', 'naga', 'oda', 'oga', 'oishi', 'okimoto', 'ooba', 'ryo', ...
    'sasaki', 'sekiya', 'sokabe', 'take', 'takiguchi', 'tarumi', 'uchino', 'wang', ...
    'yano', 'yon', 'yonemasu', 'yoshi', 'yoshida'};
gt_labels = [1:41]';
